namespace Tabsan.EduSphere.Domain.Auditing;

/// <summary>
/// Immutable audit record written whenever a privileged action is performed.
/// Uses a bigint PK (long) for efficient sequential insertion and time-range queries.
/// Rows are NEVER updated or deleted — this table is append-only by design.
/// </summary>
public class AuditLog
{
    /// <summary>Sequential integer PK. Auto-generated by the database.</summary>
    public long Id { get; private set; }

    /// <summary>
    /// FK to the user who performed the action.
    /// Nullable to handle system-initiated events (e.g. scheduled license check).
    /// </summary>
    public Guid? ActorUserId { get; private set; }

    /// <summary>Short verb describing what happened (e.g. "Login", "PublishResult", "UploadLicense").</summary>
    public string Action { get; private set; } = default!;

    /// <summary>Role of the actor at the time of action (e.g. SuperAdmin/Admin/Faculty/Student).</summary>
    public string? ActorRole { get; private set; }

    /// <summary>Name of the domain entity affected (e.g. "User", "Assignment", "LicenseState").</summary>
    public string EntityName { get; private set; } = default!;

    /// <summary>String representation of the affected entity's primary key.</summary>
    public string? EntityId { get; private set; }

    /// <summary>JSON snapshot of the entity's state BEFORE the action. Null for create operations.</summary>
    public string? OldValuesJson { get; private set; }

    /// <summary>JSON snapshot of the entity's state AFTER the action. Null for delete operations.</summary>
    public string? NewValuesJson { get; private set; }

    /// <summary>UTC timestamp of the event. Used as the clustered index for efficient range queries.</summary>
    public DateTime OccurredAt { get; private set; } = DateTime.UtcNow;

    /// <summary>Client IP address at the time of the action. Captured from HttpContext.</summary>
    public string? IpAddress { get; private set; }

    /// <summary>Client device/user agent string captured from HttpContext headers.</summary>
    public string? UserAgent { get; private set; }

    private AuditLog() { }

    /// <summary>
    /// Creates a new audit log entry. All audit writes go through this constructor
    /// to ensure no field is accidentally omitted.
    /// </summary>
    public AuditLog(string action, string entityName, string? entityId = null,
                    Guid? actorUserId = null, string? oldValuesJson = null,
                    string? newValuesJson = null, string? ipAddress = null,
                    string? actorRole = null, string? userAgent = null)
    {
        Action = action;
        EntityName = entityName;
        EntityId = entityId;
        ActorUserId = actorUserId;
        OldValuesJson = oldValuesJson;
        NewValuesJson = newValuesJson;
        IpAddress = ipAddress;
        ActorRole = actorRole;
        UserAgent = userAgent;
    }
}
